---
title: "Glacial Well Water Well Analysis"
author: "Annette Hilton"
date: "2/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Attach Packages and Data 

```{r}
# Attach packages 

library(tidyverse)
library(here)
library(janitor)

# Disable scientific notation 

options(scipen=999)

```

```{r}
# Read in the full dataset for all well water measurements for the USA 

entire_usa_gw <- readr::read_tsv("entire_usgs_usa.txt")

```

## Prep USGS Well Data to Import in ArcGIS 

```{r}
#----------------------------------------------------------------------------------
# ArcGIS Data Prep for Glacial-Well location exercise 
#----------------------------------------------------------------------------------

# Remove wells that have no date associated with them 
# Remove duplicate site values (only keep each site once) 

arc_entire_usa <- entire_usa_gw %>% 
  filter(!lev_dt == "NA") %>% 
  distinct(site_no, .keep_all = TRUE) 

# Separate latitude and longitude in separate dataframe

arc_entire_usa_glacial <- arc_entire_usa %>% 
  select(site_no, dec_lat_va, dec_long_va)
arc_entire_usa_glacial$site_no <- as.character(arc_entire_usa_glacial$site_no)

# Write to tsv for import to ArcGIS 

write_csv(arc_entire_usa_glacial, here::here("glacial_data", "arc_entire_usa_glacial.txt"))

write_csv(arc_entire_usa_glacial, here::here("glacial_data", "arc_entire_usa_glacial.csv"))


```



## Import and Work with Results from ArcGIS 

```{r}
# Import Data from ArcGIS (well sites within proximity to glacier) 

# Import wells 10 km from glacier

wells_10km <- readr::read_csv(here::here("glacial_data", "accurate_well_data", "wells_10km.txt"))


# Import wells 5 km from glacier 

wells_5km <- readr::read_csv(here::here("glacial_data", "accurate_well_data", "wells_5km.txt"))

```

```{r}
# Tidy well data from ArcGIS 

# Wells within 10 km 

wells_10_tidy <- wells_10km %>% 
  clean_names() %>% 
  mutate(site = str_remove(site, pattern = "x")) %>% 
  mutate(site_no = str_remove(site, pattern = "x")) %>% 
   select(-oid, -site) 

# Wells within 5km

wells_5_tidy <- wells_5km %>% 
  clean_names() %>% 
  mutate(site = str_remove(site, pattern = "x")) %>% 
  mutate(site_no = str_remove(site, pattern = "x")) %>% 
   select(-oid, -site)
 
```

```{r}
# Create vector from wells with site ID only 

wells_10km_vector <- wells_10_tidy %>% 
  pull(site_no)

wells_5km_vector <- wells_5_tidy %>% 
  pull(site_no)
```

```{r}
# Attempt to filter by vector/site_no

# Wells within 10km 

wells_10_usgs <- entire_usa_gw %>%
  filter(site_no %in% c(wells_10km_vector))

# Wells within 5km 

wells_5_usgs <- entire_usa_gw %>%
  filter(site_no %in% c(wells_5km_vector))


```

```{r}
# COMMENTED OUT BECAUSE METHOD ABOVE WORKS, THIS WAS JUST DOUBLE CHECKING 

# # Attempt different method using semi_join() and lat/long unique ids 
# 
# # Wells within 10km 
# 
# wells_10_usgs <- semi_join(entire_usa_gw, wells_10km, by = c("dec_lat_va", "dec_long_va"))
# 
# # Wells within 5km 
# 
# wells_5_usgs <- semi_join(entire_usa_gw, wells_5km, by = c("dec_lat_va", "dec_long_va"))
```

Constrain by number of observations 

```{r}
#--------------------------------------------------------------------------
# Constrain by number of observations for wells 10km 
#--------------------------------------------------------------------------

# Constrain by number of observations (n > 1) (total of 5937)

wells_10_usgs_no1 <- wells_10_usgs %>%
  group_by(site_no) %>%
  filter( n() > 1)

# Constrain by number of observations (n > 30) (total 4807)

wells_10_usgs_no30 <- wells_10_usgs %>%
  group_by(site_no) %>%
  filter( n() > 29)

# Constrain by number of observations ( n > 100) (total 2431)

wells_10_usgs_no100 <- wells_10_usgs %>%
  group_by(site_no) %>%
  filter( n() > 99)

```

```{r}
#---------------------------------------------------------------------------
# Constrain by number of observations for wells 5km
#---------------------------------------------------------------------------

# Constrain by number of observations (n > 1) (total of 471)

wells_5_usgs_no1 <- wells_5_usgs %>%
  group_by(site_no) %>%
  filter( n() > 1)

# Constrain by number of observations (n > 30) (total 425)

wells_5_usgs_no30 <- wells_5_usgs %>%
  group_by(site_no) %>%
  filter( n() > 29)

# Constrain by number of observations ( n > 100) (total 101)

wells_5_usgs_no100 <- wells_5_usgs %>%
  group_by(site_no) %>%
  filter( n() > 99)

```

